### ISSUE TITLE
Some license issue

### ISSUE THREAD

**Issue by tduriez** [gycm134/xMLC#1]
Hi Guy, this is a very good work, I've been looking into it with interest.

You need to indicate that it was forked from my work and remove your copyright from functions I have written and put back mine. (letting your where you did modify something is still pretty much the way to go). Commit 09593bc18b512e4aab7e2ee676df8b39f227f266 clearly shows it was ripped from [OpenMLC-Matlab-2](https://github.com/tduriez/OpenMLC-Matlab-2). Funny things is that in this commit I can find functions I wrote, with your copyright. Please correct this.

**Comment by tduriez** [comment]
![image](https://user-images.githubusercontent.com/8561582/188293253-0a0286d1-8f68-4e2b-9639-4d26c66439ae.png)
This, from [here](https://github.com/gycm134/xMLC/blob/main/MLC_tools/readmylisp_to_evaluate.m) is more than inspired, variable names and algorithm inside are all pretty much mine.  Please give credit where it belongs the correct way.

**Comment by gycm134** [comment]
Dear Thomas, 
Thank you for your message. You are perfectly right.
My apologies for this serious lack of communication.
The fork is now mentionned in the README.md file with a link to your work.
The heading of the functions from your code have also been corrected.
Feel free to contact me if you have any other concerns.

**Comment by tduriez** [comment]
Dear Guy, thank you for your swift reply and appropriate actions. Apologies accepted. Forks are very healthy and very good (now I can improve my code without having to think!) as long as everyody's work is acknowldged. Have a nice WE.
